#!/usr/bin/env python3
"""
Validation of the internal antenna model against CarMaker's shipped gain map.

This is the strongest quantitative check available for the object-list Radar
Sensor: CarMaker ships ``Data/Sensor/Radar_Default``, a 181 x 181 antenna gain
map that was generated by IPG's own "Antenna Gain Map Generator" from
``BeamWidth = 20 15``, ``ScanRange = 0 0``, ``AntennaEff = 1.0``.  Our
independent implementation of Reference Manual Equations 507/508 must reproduce
that file.

Run:
    python3 validation/validate_antenna_map.py --ipg <CarMaker install dir>
"""

from __future__ import annotations

import argparse
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np                                                # noqa: E402

from common.paths import default_carmaker_dir, missing_message, short  # noqa: E402
from radar_object_list.maps import AntennaGainMap                 # noqa: E402



def compare(ref: AntennaGainMap, gen: AntennaGainMap, label: str) -> None:
    r = np.array(ref.gain_db)
    g = np.array(gen.gain_db)
    if r.shape != g.shape:
        print(f"  {label}: shape mismatch {r.shape} vs {g.shape}")
        return
    rn = r - r.max()
    gn = g - g.max()
    diff = np.abs(gn - rn)

    def stats(mask, name):
        if mask.sum() == 0:
            print(f"    {name:<34s} (no cells)")
            return
        print(f"    {name:<34s} cells={mask.sum():6d}  "
              f"mean={diff[mask].mean():6.3f} dB  max={diff[mask].max():6.3f} dB")

    print(f"  {label}")
    print(f"    peak gain   reference = {r.max():.4f} dB   model = {g.max():.4f} dB"
          f"   (delta {g.max() - r.max():+.4f} dB)")
    stats(rn > -3.0, "inside the 3 dB main lobe")
    stats(rn > -10.0, "inside the 10 dB main lobe")
    stats((rn > -25.0) & (gn > -25.0), "everywhere above -25 dB")
    stats((rn > -40.0) & (gn > -40.0), "everywhere above -40 dB")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ipg", default=default_carmaker_dir(),
                    help="CarMaker installation dir (default: $CARMAKER_DIR)")
    args = ap.parse_args()
    if not args.ipg:
        print(missing_message())
        return

    path = os.path.join(args.ipg, "Data", "Sensor", "Radar_Default")
    if not os.path.isfile(path):
        print(f"[skip] {path} not found - point --ipg at a CarMaker installation")
        return

    ref = AntennaGainMap.load(path)
    print(f"reference map : {short(path, 4)}")
    print(f"  BeamWidth   = {ref.beam_width[0]} {ref.beam_width[1]} deg")
    print(f"  ScanRange   = {ref.scan_range[0]} {ref.scan_range[1]} deg")
    print(f"  AntennaEff  = {ref.antenna_eff}")
    print(f"  samples     = {len(ref.az)} x {len(ref.el)}, "
          f"azimuth {math.degrees(ref.az[0]):.0f}..{math.degrees(ref.az[-1]):.0f} deg")
    print(f"  peak gain   = {ref.peak_db:.4f} dB\n")

    print("Reference Manual Eq. 507/508 only "
          "(f = sinc(pi nu_y) sinc(pi nu_z), G0 = 4 pi a b / lambda^2):")
    gen_plain = AntennaGainMap.generate(ref.beam_width, ref.scan_range,
                                        ref.antenna_eff, n_samples=len(ref.az),
                                        obliquity=False)
    compare(ref, gen_plain, "documented model")

    print()
    print("Same, plus the inferred Huygens obliquity factor (1 + cos Theta)/2:")
    gen_ob = AntennaGainMap.generate(ref.beam_width, ref.scan_range,
                                     ref.antenna_eff, n_samples=len(ref.az),
                                     obliquity=True)
    compare(ref, gen_ob, "documented model + obliquity")

    # ---------------- structural checks: null positions ------------------
    print()
    print("Null positions (they fix the aperture size a, b):")
    d = np.degrees(np.array(ref.az))
    cut_az = np.array(ref.gain_db)[:, len(ref.el) // 2]
    cut_el = np.array(ref.gain_db)[len(ref.az) // 2, :]

    def first_null(cut):
        mid = len(cut) // 2
        for j in range(mid + 1, len(cut) - 1):
            if cut[j] < cut[j - 1] and cut[j] < cut[j + 1] and cut[j] < cut.max() - 25:
                return d[j]
        return float("nan")

    from radar_object_list.maps import APERTURE_BW_CONST
    a_lam = APERTURE_BW_CONST / math.radians(ref.beam_width[0])
    b_lam = APERTURE_BW_CONST / math.radians(ref.beam_width[1])
    print(f"    azimuth  : file {first_null(cut_az):5.1f} deg   "
          f"theory asin(lambda/a) = {math.degrees(math.asin(1.0 / a_lam)):5.2f} deg")
    print(f"    elevation: file {first_null(cut_el):5.1f} deg   "
          f"theory asin(lambda/b) = {math.degrees(math.asin(1.0 / b_lam)):5.2f} deg")

    # ---------------- 3 dB beam widths -----------------------------------
    def bw3(cut):
        idx = np.nonzero(cut >= cut.max() - 3.0)[0]
        return d[idx[-1]] - d[idx[0]]

    print()
    print("3 dB beam widths (sampled on the 1 deg grid of the file):")
    print(f"    azimuth  : {bw3(cut_az):.1f} deg   (parameter BeamWidth_h = "
          f"{ref.beam_width[0]} deg)")
    print(f"    elevation: {bw3(cut_el):.1f} deg   (parameter BeamWidth_v = "
          f"{ref.beam_width[1]} deg)")


if __name__ == "__main__":
    main()
